var bakeryCakesDairy = [
  {
   id: 310,
   quantity:0,
 OFF: 34,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Homogenised Toned Milk",
 productprice: 63.63,
 StrikePrice: 66,
 Brand: "Amul",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/306926_4-amul-homogenised-toned-milk.jpg",
},
{
 id: 311,
 quantity:0,
 OFF: 34,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Whole Wheat Brown Bread With Bran",
 productprice: 42.75,
 StrikePrice: 45,
 Brand: "THE BAKE SHOP",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/40082738_1-the-bake-shop-whole-wheat-brown-bread-with-bran.jpg",
},
{
 id: 312,
 quantity:0,
 OFF: 35,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Butter - Pasteurised",
 productprice: 236,
 StrikePrice: 245,
 Brand: "Amul",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/104864_7-amul-butter-pasteurised.jpg",
},
{
 id: 313,
 quantity:0,
 OFF: 54,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Butter - White",
 productprice: 456,
 StrikePrice: 480,
 Brand: "Parsi Dairy Farm",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/30009708_2-parsi-dairy-farm-butter-white.jpg",
},
{
 id: 314,
 quantity:0,
 OFF: 32,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName:
   "Sandwich Bread - White, Chemical Free 400G + Eggs - Regular 6pcs",
 productprice: 84.46,
 StrikePrice: 105,
 Brand: "Fresho",
 Date: "Standard Delivery : 10AM To 6PM",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/1204352_1-fresho-sandwich-bread-white-chemical-free-400g-eggs-regular-6pcs.jpg",
},
{
 id: 315,
 quantity:0,
 OFF: 31,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Ladi Pav - Whole Wheat",
 productprice: 38,
 StrikePrice: 40,
 Brand: "THE BAKE SHOP",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/30001077_1-the-bake-shop-ladi-pav-whole-wheat.jpg",
},
{
 id: 316,
 quantity:0,
 OFF: 45,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName:
   "THE BAKE SHOP\nBread - Whole wheat100% Atta with Multigrain Sliced",
 productprice: 61.75,
 StrikePrice: 65,
 Brand: "THE BAKE SHOP",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/30001066_1-the-bake-shop-bread-whole-wheat100-atta-with-multigrain-sliced.jpg",
},
{
 id: 317,
 quantity:0,
 OFF: 42,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Kharis - Whole Wheat",
 productprice: 61.75,
 StrikePrice: 65,
 Brand: "THE BAKE SHOP",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/30001084_2-the-bake-shop-kharis-whole-wheat.jpg",
},
{
 id: 318,
 quantity:0,
 OFF: 45,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Masti Dahi",
 productprice: 72.72,
 StrikePrice: 80,
 Brand: "Amul",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/1213630_1-amul-masti-dahi.jpg",
},
{
 id: 319,
 quantity:0,
 OFF: 41,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName:
   "Bread - Whole Wheat, Chemical Free 400G + Eggs - Table Tray 30pcs",
 productprice: 252,
 StrikePrice: 315,
 Brand: "Fresho",
 Date: "Standard Delivery : 10AM To 6PM",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/1204360_1-fresho-bread-whole-wheat-chemical-free-400g-eggs-table-tray-30pcs.jpg",
},
{
 id: 320,
 quantity:0,
 OFF: 32,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Cheese Slices",
 productprice: 73,
 StrikePrice: 76,
 Brand: "Amul",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/104759_9-amul-cheese-slices.jpg",
},
{
 id: 321,
 quantity:0,
 OFF: 34,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Premium Dahi",
 productprice: 50,
 StrikePrice: 55,
 Brand: "Amul",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/30007176_5-amul-premium-dahi.jpg",
},
{
 id: 322,
 quantity:0,
 OFF: 21,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Everyday Dairy Whitener - Milk Powder For Tea",
 productprice: 9.4,
 StrikePrice: 10,
 Brand: "Nestle",
 image:
   "https://www.bigbasket.com/media/uploads/p/s/40020214_9-nestle-everyday-dairy-whitener-milk-powder-for-tea.jpg",
},
{
 id: 323,
 quantity:0,
 OFF: 22,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName: "Cashew Based Parmesan Cheese - Rich In Nutrients",
 productprice: 248,
 StrikePrice: 250,
 Brand: "Goodmylk",
 image:
   "https://www.bigbasket.com/media/uploads/p/mm/40238302_1-goodmylk-cashew-based-parmesan-cheese-rich-in-nutrients.jpg",
},
{
 id: 324,
 quantity:0,
 OFF: 24,
 Date: "Standard Delivery : 10AM To 6PM",
 QtyPiece: "Price of 1 Kg",
 QtyPieceForOneElement: "1 Kg",
 productName:
   "Toastea Premium Bake Rusk With Goodness Of Elaichi, Sooji & Wheat",
 productprice: 31.18,
 StrikePrice: 40,
 Brand: "Britannia",
 image:
   "https://www.bigbasket.com/media/uploads/p/mm/312568_18-britannia-toastea-premium-bake-rusk-with-goodness-of-elaichi-sooji-wheat.jpg",
},
];
export default bakeryCakesDairy;