
var cleaningHousehold = [
  {
    id: 610,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Toilet Cleaner Liquid, Original",
    productprice: 495,
    StrikePrice: 585,
    Brand: "Harpic",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1207190_6-harpic-disinfectant-toilet-cleaner-liquid-original.jpg",
  },
  {
    id: 611,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Surface & Floor Cleaner Liquid, Citrus",
    productprice: 314,
    StrikePrice: 399,
    Brand: "Lizol",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/249154_12-lizol-disinfectant-surface-floor-cleaner-liquid-citrus.jpg",
  },
  {
    id: 612,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 42,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dishwash Liquid Gel - Lemon",
    productprice: 182,
    StrikePrice: 209,
    Brand: "Vim",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40001181_9-vim-dishwash-liquid-gel-lemon.jpg",
  },
  {
    id: 613,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 44,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Easy Wash Detergent Powder",
    productprice: 167,
    StrikePrice: 205,
    Brand: "Surf Excel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/266945_19-surf-excel-easy-wash-detergent-powder.jpg",
  },
  {
    id: 614,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Matic Liquid Detergent - Top Load",
    productprice: 595.57,
    StrikePrice: 700,
    Brand: "Surf Excel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1207310_6-surf-excel-matic-liquid-detergent-top-load.jpg",
  },
  {
    id: 615,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 31,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Bathroom Cleaner Liquid, Lemon",
    productprice: 300,
    StrikePrice: 378,
    Brand: "Harpic",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1208843_4-harpic-disinfectant-bathroom-cleaner-liquid-lemon.jpg",
  },
  {
    id: 616,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 32,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cleaning Lime Scale Salt",
    productprice: 150,
    StrikePrice: 156,
    Brand: "Finish",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1201634_3-finish-cleaning-lime-scale-salt.jpg",
  },
  {
    id: 617,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Harpic Toilet Cleaner, Original 1 L + Lizol Surface Cleaner, Citrus 2 L",
    productprice: 479,
    StrikePrice: 568,
    Brand: "BB-Combo",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1208977_3-bb-combo-harpic-toilet-cleaner-original-1-l-lizol-surface-cleaner-citrus-2-l.jpg",
  },
  {
    id: 618,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dishwash Liquid Gel - Lemon",
    productprice: 161.35,
    StrikePrice: 186,
    Brand: "Vim",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/307195_18-vim-dishwash-liquid-gel-lemon.jpg",
  },
  {
    id: 619,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 52,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Pooja Oil",
    productprice: 93.25,
    StrikePrice: 100,
    Brand: "Mangalmai",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40080807_1-mangalmai-pooja-oil.jpg",
  },
  {
    id: 620,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 21,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "After Wash Morning Fresh Fabric Conditioner",
    productprice: 400,
    StrikePrice: 480,
    Brand: "Comfort",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40130608_7-comfort-after-wash-morning-fresh-fabric-conditioner.jpg",
  },
  {
    id: 621,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Detergent Washing Powder - Matic Front Load",
    productprice: 191.88,
    StrikePrice: 1077,
    Brand: "Ariel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1214198_1-ariel-detergent-washing-powder-matic-front-load.jpg",
  },
  {
    id: 622,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Garbage Bags - Oxo Biodegradable Medium, Green, (19x21 Inches)",
    productprice: 185.25,
    StrikePrice: 195,
    Brand: "BB Home",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212117_3-bb-home-garbage-bags-oxo-biodegradable-medium-green-19x21-inches.jpg",
  },
];
export default cleaningHousehold;