var foodOilAndMasala = [
  {
    id: 210,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Sweet Corn",
    productprice: 45,
    StrikePrice: 56.12,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40004992_14-fresho-sweet-corn.jpg",
  },
  {
    id: 211,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Farm Cow Ghee",
    productprice: 494,
    StrikePrice: 520,
    Brand: "Parsi Dairy Farm",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40126129_2-parsi-dairy-farm-cow-ghee.jpg",
  },
  {
    id: 212,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    Date: "Standard Delivery : 10AM To 6PM",
    productName: "Sugar - Refined",
    productprice: 48.48,
    StrikePrice: 60,
    Brand: "Madhur",
    image:
      "https://www.bigbasket.com/media/uploads/bpi/mumbai/s/244096_1-madhur-sugar-refined.jpg",
  },
  {
    id: 213,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Unpolished Toor Dal/Arhar Dal",
    productprice: 136,
    StrikePrice: 179,
    Brand: "Tata Sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40000291_8-tata-sampann-unpolished-toor-dalarhar-dal.jpg",
  },
  {
    id: 214,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Sun Lite-Sunflower Refined Oil",
    productprice: 152,
    StrikePrice: 180,
    Brand: "Fortune",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/274145_14-fortune-sun-lite-sunflower-refined-oil.jpg",
  },
  {
    id: 215,
    quantity:0,
    OFF: 31,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Iodized",
    productprice: 21.21,
    StrikePrice: 24,
    Brand: "Tata sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/241600_5-tata-salt-iodized.jpg",
  },
  {
    id: 216,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Gold-Pro Healthy Lifestyle Edible Oil\n",
    productprice: 545.14,
    StrikePrice: 630,
    Brand: "Saffola",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1203529_5-saffola-gold-pro-healthy-lifestyle-edible-oil.jpg",
  },
  {
    id: 217,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Poha/Avalakki/Aval/Chivda-Thick",
    productprice: 52,
    StrikePrice: 80,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000431_18-bb-royal-pohaavalakkiavalchivda-thick.jpg",
  },
  {
    id: 218,
    quantity:0,
    OFF: 25,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Oil - Extra Light 2 L Bottle + Durum Wheat Pasta Penne Rigate 500 g Pouch",
    productprice: 1344.35,
    StrikePrice: 2850.2,
    Brand: "BORGESlive",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212929_1-borges-olive-oil-extra-light-2-l-bottle-durum-wheat-pasta-penne-rigate-500-g-pouch.jpg",
  },
  {
    id: 219,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Select Sharbati Atta-100% MP Whole Wheat, Rotis Stay Softer For Longer",
    productprice: 469,
    StrikePrice: 610,
    Brand: "Aashirvaad",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40236231_1-aashirvaad-select-sharbati-atta-100-mp-whole-wheat-rotis-stay-softer-for-longer.jpg",
  },
  {
    id: 220,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Organic - Almond/Badam",
    productprice: 101,
    StrikePrice: 195,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40072510_14-bb-royal-organic-almondbadam.jpg",
  },
  {
    id: 221,
    quantity:0,
    OFF: 41,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Oil - Groundnut",
    productprice: 962,
    StrikePrice: 1175,
    Brand: "Dhara",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/134006_5-dhara-oil-groundnut.jpg",
  },
  {
    id: 222,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Fortune Premium Kachi Ghani Pure Mustard Oil",
    productprice: 182,
    StrikePrice: 227,
    Brand: "Fortune",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/276756_8-fortune-fortune-premium-kachi-ghani-pure-mustard-oil.jpg",
  },
  {
    id: 223,
    quantity:0,
    OFF: 44,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Lite - 15% Low Sodium Iodised Salt",
    productprice: 26.26,
    StrikePrice: 40,
    Brand: "Tata Sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/241601_6-tata-salt-lite-15-low-sodium-iodised-salt.jpg",
  },
  {
    id: 224,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Organic - Cardamom Green/Hirvi Velchi",
    productprice: 299.5,
    StrikePrice: 599.5,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40203900_1-bb-royal-organic-cardamom-green.jpg",
  },
  {
    id: 225,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Basmati Rice - Rozana Premium",
    productprice: 818,
    StrikePrice: 1020.2,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/1211909_1-bb-royal-basmati-rice-rozana-premium.jpg",
  },
];
  export default foodOilAndMasala;