var snacksBrandedFood = [
  {
    id: 410,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "2-Minute Instant Noodles - Masala",
    productprice: 83.35,
    StrikePrice: 96.5,
    Brand: "MAGGI",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/266109_18-maggi-2-minute-instant-noodles-masala.jpg",
  },
  {
    id: 411,
    quantity:0,
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Frozen Green Peas",
    productprice: 99.5,
    StrikePrice: 135,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40192104_2-fresho-frozen-green-peas.jpg",
  },
  {
    id: 412,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Good Day Cashew Cookies",
    productprice: 90.12,
    StrikePrice: 120,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40083744_6-britannia-good-day-cashew-cookies.jpg",
  },
  {
    id: 413,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato Chips - Indias Magic Masala",
    productprice: 65.62,
    StrikePrice: 100,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212516_4-lays-potato-chips-indias-magic-masala.jpg",
  },
  {
    id: 414,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Fresh Tomato Ketchup",
    productprice: 101.99,
    StrikePrice: 120,
    Brand: "Kissan",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40029538_33-kissan-fresh-tomato-ketchup.jpg",
  },
  {
    id: 415,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "NutriChoice Digestive High Fibre Biscuits",
    productprice: 84.84,
    StrikePrice: 100,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1206706_2-britannia-nutrichoice-digestive-high-fibre-biscuits.jpg",
  },
  {
    id: 416,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Namkeen - Bhujia Sev",
    productprice: 187.2,
    StrikePrice: 240,
    Brand: "Haldirams",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/100022552_1-haldirams-namkeen-bhujia-sev.jpg",
  },
  {
    id: 417,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Oats Breakfast Cereal - Rich In Protein, Dietary Fibre, Nutritious, Easy To Cook",
    productprice: 200,
    StrikePrice: 273,
    Brand: "Quaker",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/284405_13-quaker-oats-breakfast-cereal-rich-in-protein-dietary-fibre-nutritious-easy-to-cook.jpg",
  },
  {
    id: 418,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Hommade - Coconut Milk",
    productprice: 207,
    StrikePrice: 225,
    Brand: "Dabur",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1205129_5-dabur-hommade-coconut-milk.jpg",
  },
  {
    id: 419,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato Chips - American Style Cream & Onion Flavour",
    productprice: 65.65,
    StrikePrice: 100,
    Brand: "Lays",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212514_5-lays-potato-chips-american-style-cream-onion-flavour.jpg",
  },
  {
    id: 420,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Namkeen - Bikaneri Bhujia",
    productprice: 290.99,
    StrikePrice: 300,
    Brand: "Bikaji",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30011826_7-bikaji-namkeen-bikaneri-bhujia.jpg",
  },
  {
    id: 421,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Nice Time - Sugar Showered Coconut Biscuits",
    productprice: 132.45,
    StrikePrice: 150,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1203920_3-britannia-nice-time-sugar-showered-coconut-biscuits.jpg",
  },
  {
    id: 422,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Gluco Biscuits - Parle-G",
    productprice: 70.88,
    StrikePrice: 75,
    Brand: "Parle",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/102102_4-parle-gluco-biscuits-parle-g.jpg",
  },
  {
    id: 423,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Britannia Little Hearts Classic - Sugar Sprinkled, Heart Shaped Biscuits",
    productprice: 51.23,
    StrikePrice: 60,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1200143_10-britannia-britannia-little-hearts-classic-sugar-sprinkled-heart-shaped-biscuits.jpg",
  },
  {
    id: 424,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dark Fantasy - Choco Fills",
    productprice: 374.22,
    StrikePrice: 450,
    Brand: "Sunfeast",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/1202647_3-sunfeast-dark-fantasy-choco-fills.jpg",
  },
];
export default snacksBrandedFood;