var fruitVeg = [
  {
    id: 110,
    quantity:0,
    OFF: 20,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Onion",
    productprice: 32.32,
    StrikePrice: 45,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000150_19-fresho-onion.jpg",
  },
  {
    id: 111,
    quantity:0,
    OFF: 50,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Tomato Hybrid",
    productprice: 36,
    StrikePrice: 45,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000201_15-fresho-tomato-hybrid.jpg",
  },
  {
    id: 112,
    quantity:0,
    OFF: 51,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cauliflower/Phul Kobi",
    productprice: 45,
    StrikePrice: 50.2,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000074_19-fresho-cauliflower.jpg",
  },
  {
    id: 113,
    quantity:0,
    OFF: 65,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Ladies Finger/Bhendi",
    productprice: 21.21,
    StrikePrice: 40,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000143_14-fresho-ladies-finger.jpg",
  },
  {
    id: 114,
    quantity:0,
    OFF: 25,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Mushrooms",
    productprice: 39.39,
    StrikePrice: 57.5,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000273_16-fresho-mushrooms-button.jpg",
  },
  {
    id: 115,
    quantity:0,
    OFF: 21,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Capsicum/Dhobli Mirchi",
    productprice: 68.68,
    StrikePrice: 113,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000069_20-fresho-capsicum-green.jpg",
  },
  {
    id: 116,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Kakdi- Hirvi",
    productprice: 44.44,
    StrikePrice: 65,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000103_16-fresho-cucumber.jpg",
  },
  {
    id: 117,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Banana/Kele",
    productprice: 90,
    StrikePrice: 112,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000031_21-fresho-banana-yelakki.jpg",
  },
  {
    id: 118,
    quantity:0,
    OFF: 35,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Carrot/Gajar",
    productprice: 119,
    StrikePrice: 140,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000271_13-fresho-carrot-ooty.jpg",
  },
  {
    id: 119,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Lemon-Organically",
    productprice: 90,
    StrikePrice: 112,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/50000526_6-fresho-lemon-organically-grown.jpg",
  },
  {
    id: 120,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Beetroot/Beet",
    productprice: 56,
    StrikePrice: 77.56,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000047_21-fresho-beetroot.jpg",
  },
  {
    id: 121,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Tender Coconut",
    productprice: 41,
    StrikePrice: 51,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40057966_2-fresho-tender-coconut-medium.jpg",
  },
  {
    id: 122,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato-New Crop",
    productprice: 25,
    StrikePrice: 31,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40048457_7-fresho-potato-new-crop.jpg",
  },
  {
    id: 123,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Baby Apple",
    productprice: 179,
    StrikePrice: 223.19,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40226802_1-fresho-baby-apple-shimla.jpg",
  },
  {
    id: 124,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Coriander/Sambhar",
    productprice: 4.4,
    StrikePrice: 5.5,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000097_19-fresho-coriander-leaves.jpg",
  },
  {
    id: 125,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Beans-French,Ring",
    productprice: 50.5,
    StrikePrice: 83.75,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000044_42-fresho-beans-french-ring.jpg",
  },
  {
    id: 126,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Ginger",
    productprice: 50.5,
    StrikePrice: 95.47,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40029980_3-fresho-ginger-organically-grown.jpg",
  },
  {
    id: 127,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Chilli-Hybrid",
    productprice: 137.15,
    StrikePrice: 171,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/30000645_12-fresho-chilli-hybrid.jpg",
  },
  {
    id: 128,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Radish White",
    productprice: 36.61,
    StrikePrice: 61.21,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/10000166_16-fresho-radish-white.jpg",
  },
];
  export default  fruitVeg ;
