var FruitVeg = [
  {
    id: 110,
    quantity:0,
    OFF: 20,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Onion",
    productprice: 32.32,
    StrikePrice: 45,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000150_19-fresho-onion.jpg",
  },
  {
    id: 111,
    quantity:0,
    OFF: 50,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Tomato Hybrid",
    productprice: 36,
    StrikePrice: 45,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000201_15-fresho-tomato-hybrid.jpg",
  },
  {
    id: 112,
    quantity:0,
    OFF: 51,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cauliflower/Phul Kobi",
    productprice: 45,
    StrikePrice: 50.2,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000074_19-fresho-cauliflower.jpg",
  },
  {
    id: 113,
    quantity:0,
    OFF: 65,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Ladies Finger/Bhendi",
    productprice: 21.21,
    StrikePrice: 40,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000143_14-fresho-ladies-finger.jpg",
  },
  {
    id: 114,
    quantity:0,
    OFF: 25,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Mushrooms",
    productprice: 39.39,
    StrikePrice: 57.5,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000273_16-fresho-mushrooms-button.jpg",
  },
  {
    id: 115,
    quantity:0,
    OFF: 21,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Capsicum/Dhobli Mirchi",
    productprice: 68.68,
    StrikePrice: 113,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000069_20-fresho-capsicum-green.jpg",
  },
  {
    id: 116,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Kakdi- Hirvi",
    productprice: 44.44,
    StrikePrice: 65,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000103_16-fresho-cucumber.jpg",
  },
  {
    id: 117,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Banana/Kele",
    productprice: 90,
    StrikePrice: 112,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000031_21-fresho-banana-yelakki.jpg",
  },
  {
    id: 118,
    quantity:0,
    OFF: 35,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Carrot/Gajar",
    productprice: 119,
    StrikePrice: 140,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000271_13-fresho-carrot-ooty.jpg",
  },
  {
    id: 119,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Lemon-Organically",
    productprice: 90,
    StrikePrice: 112,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/50000526_6-fresho-lemon-organically-grown.jpg",
  },
  {
    id: 120,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Beetroot/Beet",
    productprice: 56,
    StrikePrice: 77.56,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000047_21-fresho-beetroot.jpg",
  },
  {
    id: 121,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Tender Coconut",
    productprice: 41,
    StrikePrice: 51,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40057966_2-fresho-tender-coconut-medium.jpg",
  },
  {
    id: 122,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato-New Crop",
    productprice: 25,
    StrikePrice: 31,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40048457_7-fresho-potato-new-crop.jpg",
  },
  {
    id: 123,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Baby Apple",
    productprice: 179,
    StrikePrice: 223.19,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40226802_1-fresho-baby-apple-shimla.jpg",
  },
  {
    id: 124,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Coriander/Sambhar",
    productprice: 4.4,
    StrikePrice: 5.5,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000097_19-fresho-coriander-leaves.jpg",
  },
  {
    id: 125,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Beans-French,Ring",
    productprice: 50.5,
    StrikePrice: 83.75,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000044_42-fresho-beans-french-ring.jpg",
  },
  {
    id: 126,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Ginger",
    productprice: 50.5,
    StrikePrice: 95.47,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40029980_3-fresho-ginger-organically-grown.jpg",
  },
  {
    id: 127,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Chilli-Hybrid",
    productprice: 137.15,
    StrikePrice: 171,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/30000645_12-fresho-chilli-hybrid.jpg",
  },
  {
    id: 128,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Radish White",
    productprice: 36.61,
    StrikePrice: 61.21,
    Brand: "BB-Combo",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/10000166_16-fresho-radish-white.jpg",
  },
];
console.log(FruitVeg.length);
var foodOilAndMasala = [
  {
    id: 210,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Sweet Corn",
    productprice: 45,
    StrikePrice: 56.12,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40004992_14-fresho-sweet-corn.jpg",
  },
  {
    id: 211,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Farm Cow Ghee",
    productprice: 494,
    StrikePrice: 520,
    Brand: "Parsi Dairy Farm",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40126129_2-parsi-dairy-farm-cow-ghee.jpg",
  },
  {
    id: 212,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    Date: "Standard Delivery : 10AM To 6PM",
    productName: "Sugar - Refined",
    productprice: 48.48,
    StrikePrice: 60,
    Brand: "Madhur",
    image:
      "https://www.bigbasket.com/media/uploads/bpi/mumbai/s/244096_1-madhur-sugar-refined.jpg",
  },
  {
    id: 213,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Unpolished Toor Dal/Arhar Dal",
    productprice: 136,
    StrikePrice: 179,
    Brand: "Tata Sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40000291_8-tata-sampann-unpolished-toor-dalarhar-dal.jpg",
  },
  {
    id: 214,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Sun Lite-Sunflower Refined Oil",
    productprice: 152,
    StrikePrice: 180,
    Brand: "Fortune",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/274145_14-fortune-sun-lite-sunflower-refined-oil.jpg",
  },
  {
    id: 215,
    quantity:0,
    OFF: 31,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Iodized",
    productprice: 21.21,
    StrikePrice: 24,
    Brand: "Tata sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/241600_5-tata-salt-iodized.jpg",
  },
  {
    id: 216,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Gold-Pro Healthy Lifestyle Edible Oil\n",
    productprice: 545.14,
    StrikePrice: 630,
    Brand: "Saffola",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1203529_5-saffola-gold-pro-healthy-lifestyle-edible-oil.jpg",
  },
  {
    id: 217,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Poha/Avalakki/Aval/Chivda-Thick",
    productprice: 52,
    StrikePrice: 80,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000431_18-bb-royal-pohaavalakkiavalchivda-thick.jpg",
  },
  {
    id: 218,
    quantity:0,
    OFF: 25,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Oil - Extra Light 2 L Bottle + Durum Wheat Pasta Penne Rigate 500 g Pouch",
    productprice: 1344.35,
    StrikePrice: 2850.2,
    Brand: "BORGESlive",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212929_1-borges-olive-oil-extra-light-2-l-bottle-durum-wheat-pasta-penne-rigate-500-g-pouch.jpg",
  },
  {
    id: 219,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Select Sharbati Atta-100% MP Whole Wheat, Rotis Stay Softer For Longer",
    productprice: 469,
    StrikePrice: 610,
    Brand: "Aashirvaad",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40236231_1-aashirvaad-select-sharbati-atta-100-mp-whole-wheat-rotis-stay-softer-for-longer.jpg",
  },
  {
    id: 220,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Organic - Almond/Badam",
    productprice: 101,
    StrikePrice: 195,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40072510_14-bb-royal-organic-almondbadam.jpg",
  },
  {
    id: 221,
    quantity:0,
    OFF: 41,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Oil - Groundnut",
    productprice: 962,
    StrikePrice: 1175,
    Brand: "Dhara",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/134006_5-dhara-oil-groundnut.jpg",
  },
  {
    id: 222,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Fortune Premium Kachi Ghani Pure Mustard Oil",
    productprice: 182,
    StrikePrice: 227,
    Brand: "Fortune",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/276756_8-fortune-fortune-premium-kachi-ghani-pure-mustard-oil.jpg",
  },
  {
    id: 223,
    quantity:0,
    OFF: 44,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Lite - 15% Low Sodium Iodised Salt",
    productprice: 26.26,
    StrikePrice: 40,
    Brand: "Tata Sampann",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/241601_6-tata-salt-lite-15-low-sodium-iodised-salt.jpg",
  },
  {
    id: 224,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Organic - Cardamom Green/Hirvi Velchi",
    productprice: 299.5,
    StrikePrice: 599.5,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40203900_1-bb-royal-organic-cardamom-green.jpg",
  },
  {
    id: 225,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Basmati Rice - Rozana Premium",
    productprice: 818,
    StrikePrice: 1020.2,
    Brand: "BB-Royal",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/1211909_1-bb-royal-basmati-rice-rozana-premium.jpg",
  },
];

var bakeryCakesDairy = [
     {
      id: 310,
      quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Homogenised Toned Milk",
    productprice: 63.63,
    StrikePrice: 66,
    Brand: "Amul",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/306926_4-amul-homogenised-toned-milk.jpg",
  },
  {
    id: 311,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Whole Wheat Brown Bread With Bran",
    productprice: 42.75,
    StrikePrice: 45,
    Brand: "THE BAKE SHOP",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40082738_1-the-bake-shop-whole-wheat-brown-bread-with-bran.jpg",
  },
  {
    id: 312,
    quantity:0,
    OFF: 35,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Butter - Pasteurised",
    productprice: 236,
    StrikePrice: 245,
    Brand: "Amul",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/104864_7-amul-butter-pasteurised.jpg",
  },
  {
    id: 313,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Butter - White",
    productprice: 456,
    StrikePrice: 480,
    Brand: "Parsi Dairy Farm",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30009708_2-parsi-dairy-farm-butter-white.jpg",
  },
  {
    id: 314,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Sandwich Bread - White, Chemical Free 400G + Eggs - Regular 6pcs",
    productprice: 84.46,
    StrikePrice: 105,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1204352_1-fresho-sandwich-bread-white-chemical-free-400g-eggs-regular-6pcs.jpg",
  },
  {
    id: 315,
    quantity:0,
    OFF: 31,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Ladi Pav - Whole Wheat",
    productprice: 38,
    StrikePrice: 40,
    Brand: "THE BAKE SHOP",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30001077_1-the-bake-shop-ladi-pav-whole-wheat.jpg",
  },
  {
    id: 316,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "THE BAKE SHOP\nBread - Whole wheat100% Atta with Multigrain Sliced",
    productprice: 61.75,
    StrikePrice: 65,
    Brand: "THE BAKE SHOP",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30001066_1-the-bake-shop-bread-whole-wheat100-atta-with-multigrain-sliced.jpg",
  },
  {
    id: 317,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Kharis - Whole Wheat",
    productprice: 61.75,
    StrikePrice: 65,
    Brand: "THE BAKE SHOP",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30001084_2-the-bake-shop-kharis-whole-wheat.jpg",
  },
  {
    id: 318,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Masti Dahi",
    productprice: 72.72,
    StrikePrice: 80,
    Brand: "Amul",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1213630_1-amul-masti-dahi.jpg",
  },
  {
    id: 319,
    quantity:0,
    OFF: 41,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Bread - Whole Wheat, Chemical Free 400G + Eggs - Table Tray 30pcs",
    productprice: 252,
    StrikePrice: 315,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1204360_1-fresho-bread-whole-wheat-chemical-free-400g-eggs-table-tray-30pcs.jpg",
  },
  {
    id: 320,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cheese Slices",
    productprice: 73,
    StrikePrice: 76,
    Brand: "Amul",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/104759_9-amul-cheese-slices.jpg",
  },
  {
    id: 321,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Premium Dahi",
    productprice: 50,
    StrikePrice: 55,
    Brand: "Amul",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30007176_5-amul-premium-dahi.jpg",
  },
  {
    id: 322,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Everyday Dairy Whitener - Milk Powder For Tea",
    productprice: 9.4,
    StrikePrice: 10,
    Brand: "Nestle",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40020214_9-nestle-everyday-dairy-whitener-milk-powder-for-tea.jpg",
  },
  {
    id: 323,
    quantity:0,
    OFF: 22,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cashew Based Parmesan Cheese - Rich In Nutrients",
    productprice: 248,
    StrikePrice: 250,
    Brand: "Goodmylk",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/40238302_1-goodmylk-cashew-based-parmesan-cheese-rich-in-nutrients.jpg",
  },
  {
    id: 324,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Toastea Premium Bake Rusk With Goodness Of Elaichi, Sooji & Wheat",
    productprice: 31.18,
    StrikePrice: 40,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/312568_18-britannia-toastea-premium-bake-rusk-with-goodness-of-elaichi-sooji-wheat.jpg",
  },
];

var snacksBrandedFood = [
  {
    id: 410,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "2-Minute Instant Noodles - Masala",
    productprice: 83.35,
    StrikePrice: 96.5,
    Brand: "MAGGI",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/266109_18-maggi-2-minute-instant-noodles-masala.jpg",
  },
  {
    id: 411,
    quantity:0,
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Frozen Green Peas",
    productprice: 99.5,
    StrikePrice: 135,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40192104_2-fresho-frozen-green-peas.jpg",
  },
  {
    id: 412,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Good Day Cashew Cookies",
    productprice: 90.12,
    StrikePrice: 120,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40083744_6-britannia-good-day-cashew-cookies.jpg",
  },
  {
    id: 413,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato Chips - Indias Magic Masala",
    productprice: 65.62,
    StrikePrice: 100,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212516_4-lays-potato-chips-indias-magic-masala.jpg",
  },
  {
    id: 414,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Fresh Tomato Ketchup",
    productprice: 101.99,
    StrikePrice: 120,
    Brand: "Kissan",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40029538_33-kissan-fresh-tomato-ketchup.jpg",
  },
  {
    id: 415,
    quantity:0,
    OFF: 24,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "NutriChoice Digestive High Fibre Biscuits",
    productprice: 84.84,
    StrikePrice: 100,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1206706_2-britannia-nutrichoice-digestive-high-fibre-biscuits.jpg",
  },
  {
    id: 416,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Namkeen - Bhujia Sev",
    productprice: 187.2,
    StrikePrice: 240,
    Brand: "Haldirams",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/100022552_1-haldirams-namkeen-bhujia-sev.jpg",
  },
  {
    id: 417,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Oats Breakfast Cereal - Rich In Protein, Dietary Fibre, Nutritious, Easy To Cook",
    productprice: 200,
    StrikePrice: 273,
    Brand: "Quaker",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/284405_13-quaker-oats-breakfast-cereal-rich-in-protein-dietary-fibre-nutritious-easy-to-cook.jpg",
  },
  {
    id: 418,
    quantity:0,
    OFF: 21,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Hommade - Coconut Milk",
    productprice: 207,
    StrikePrice: 225,
    Brand: "Dabur",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1205129_5-dabur-hommade-coconut-milk.jpg",
  },
  {
    id: 419,
    quantity:0,
    OFF: 32,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Potato Chips - American Style Cream & Onion Flavour",
    productprice: 65.65,
    StrikePrice: 100,
    Brand: "Lays",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212514_5-lays-potato-chips-american-style-cream-onion-flavour.jpg",
  },
  {
    id: 420,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Namkeen - Bikaneri Bhujia",
    productprice: 290.99,
    StrikePrice: 300,
    Brand: "Bikaji",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30011826_7-bikaji-namkeen-bikaneri-bhujia.jpg",
  },
  {
    id: 421,
    quantity:0,
    OFF: 54,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Nice Time - Sugar Showered Coconut Biscuits",
    productprice: 132.45,
    StrikePrice: 150,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1203920_3-britannia-nice-time-sugar-showered-coconut-biscuits.jpg",
  },
  {
    id: 422,
    quantity:0,
    OFF: 34,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Gluco Biscuits - Parle-G",
    productprice: 70.88,
    StrikePrice: 75,
    Brand: "Parle",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/102102_4-parle-gluco-biscuits-parle-g.jpg",
  },
  {
    id: 423,
    quantity:0,
    OFF: 42,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Britannia Little Hearts Classic - Sugar Sprinkled, Heart Shaped Biscuits",
    productprice: 51.23,
    StrikePrice: 60,
    Brand: "Britannia",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1200143_10-britannia-britannia-little-hearts-classic-sugar-sprinkled-heart-shaped-biscuits.jpg",
  },
  {
    id: 424,
    quantity:0,
    OFF: 45,
    Date: "Standard Delivery : 10AM To 6PM",
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dark Fantasy - Choco Fills",
    productprice: 374.22,
    StrikePrice: 450,
    Brand: "Sunfeast",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/1202647_3-sunfeast-dark-fantasy-choco-fills.jpg",
  },
];

var eggMealFish = [
  {
    id: 510,
    quantity:0,
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Eggs - Regular",
    productprice: 92.92,
    StrikePrice: 130,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1203477_2-fresho-eggs-regular.jpg",
  },
  {
    id: 511,
    quantity:0,
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Chicken Breast - Boneless, Antibiotic Residue-Free",
    productprice: 430,
    StrikePrice: 690,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10001001_7-fresho-chicken-breast-boneless-antibiotic-residue-free.jpg",
  },
  {
    id: 512,
    quantity:0,
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free",
    productprice: 216,
    StrikePrice: 275,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
  },
  {
    id: 513,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Chicken Breast - Boneless",
    productprice: 137.75,
    StrikePrice: 145,
    Brand: "Zorabian",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/30001413_5-zorabian-chicken-breast-boneless.jpg",
  },
  {
    id: 514,
    quantity:0,
    OFF: 42,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Fresho Chicken Curry Cut Without Skin 1 kg + Kara Coconut Milk - Classic 400 ml",
    productprice: 384.65,
    StrikePrice: 595,
    Brand: "BB-Combo",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1213732_1-bb-combo-fresho-chicken-curry-cut-without-skin-1-kg-kara-coconut-milk-classic-400-ml.jpg",
  },
  {
    id: 515,
    quantity:0,
    OFF: 45,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Chicken Curry Cut 1kg + Seer Fish Slice/Steaks 500 g",
    productprice: 991,
    StrikePrice: 1752,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1215095_1-fresho-chicken-curry-cut-1kg-seer-fish-slicesteaks-500-g.jpg",
  },
  {
    id: 516,
    quantity:0,
    OFF: 21,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Fresho Meat Chicken Curry Cut Without Skin 1kg + Everest Chicken Masala 100g",
    productprice: 331.2,
    StrikePrice: 539,
    Brand: "BB-Combo",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1202514_1-bb-combo-fresho-meat-chicken-curry-cut-without-skin-1kg-everest-chicken-masala-100g.jpg",
  },
  {
    id: 517,
    quantity:0,
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Fresho Chicken Breast Boneless 4-5 pcs 500g +Kara Coconut Milk UHT Classic 200ml",
    productprice: 332.15,
    StrikePrice: 425,
    Brand: "BB-Combo",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1213733_1-bb-combo-fresho-chicken-breast-boneless-4-5-pcs-500g-kara-coconut-milk-uht-classic-200ml.jpg",
  },
  {
    id: 518,
    quantity:0,
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Rohu Fish - Large, Curry Cut/Bengali Cut, Preservative Free, 12-15 pcs",
    productprice: 413.36,
    StrikePrice: 620,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/10000756_34-fresho-rohu-fish-large-curry-cutbengali-cut-preservative-free-12-15-pcs.jpg",
  },
  {
    id: 519,
    quantity:0,
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Desi Rohu Fish Steak - Pre Marinated, Ready To Cook",
    productprice: 269,
    StrikePrice: 763,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40240474_4-fresho-desi-rohu-fish-steak-pre-marinated-ready-to-cook.jpg",
  },
  {
    id: 520,
    quantity:0,
    OFF: 55,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Chicken Leg - Without Skin, Antibiotic Residue-Free, 3-4 pcs",
    productprice: 325,
    StrikePrice: 435,
    Brand: "Fresho",
    Date: "Standard Delivery : 10AM To 6PM",
    image:
      "https://www.bigbasket.com/media/uploads/p/mm/10000912_9-fresho-chicken-leg-without-skin-antibiotic-residue-free-3-4-pcs.jpg",
  },
];

var cleaningHousehold = [
  {
    id: 610,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Toilet Cleaner Liquid, Original",
    productprice: 495,
    StrikePrice: 585,
    Brand: "Harpic",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1207190_6-harpic-disinfectant-toilet-cleaner-liquid-original.jpg",
  },
  {
    id: 611,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 24,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Surface & Floor Cleaner Liquid, Citrus",
    productprice: 314,
    StrikePrice: 399,
    Brand: "Lizol",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/249154_12-lizol-disinfectant-surface-floor-cleaner-liquid-citrus.jpg",
  },
  {
    id: 612,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 42,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dishwash Liquid Gel - Lemon",
    productprice: 182,
    StrikePrice: 209,
    Brand: "Vim",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40001181_9-vim-dishwash-liquid-gel-lemon.jpg",
  },
  {
    id: 613,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 44,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Easy Wash Detergent Powder",
    productprice: 167,
    StrikePrice: 205,
    Brand: "Surf Excel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/266945_19-surf-excel-easy-wash-detergent-powder.jpg",
  },
  {
    id: 614,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Matic Liquid Detergent - Top Load",
    productprice: 595.57,
    StrikePrice: 700,
    Brand: "Surf Excel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1207310_6-surf-excel-matic-liquid-detergent-top-load.jpg",
  },
  {
    id: 615,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 31,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Disinfectant Bathroom Cleaner Liquid, Lemon",
    productprice: 300,
    StrikePrice: 378,
    Brand: "Harpic",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1208843_4-harpic-disinfectant-bathroom-cleaner-liquid-lemon.jpg",
  },
  {
    id: 616,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 32,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Cleaning Lime Scale Salt",
    productprice: 150,
    StrikePrice: 156,
    Brand: "Finish",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1201634_3-finish-cleaning-lime-scale-salt.jpg",
  },
  {
    id: 617,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 34,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Harpic Toilet Cleaner, Original 1 L + Lizol Surface Cleaner, Citrus 2 L",
    productprice: 479,
    StrikePrice: 568,
    Brand: "BB-Combo",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1208977_3-bb-combo-harpic-toilet-cleaner-original-1-l-lizol-surface-cleaner-citrus-2-l.jpg",
  },
  {
    id: 618,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 54,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Dishwash Liquid Gel - Lemon",
    productprice: 161.35,
    StrikePrice: 186,
    Brand: "Vim",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/307195_18-vim-dishwash-liquid-gel-lemon.jpg",
  },
  {
    id: 619,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 52,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Pooja Oil",
    productprice: 93.25,
    StrikePrice: 100,
    Brand: "Mangalmai",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40080807_1-mangalmai-pooja-oil.jpg",
  },
  {
    id: 620,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 21,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "After Wash Morning Fresh Fabric Conditioner",
    productprice: 400,
    StrikePrice: 480,
    Brand: "Comfort",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/40130608_7-comfort-after-wash-morning-fresh-fabric-conditioner.jpg",
  },
  {
    id: 621,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName: "Detergent Washing Powder - Matic Front Load",
    productprice: 191.88,
    StrikePrice: 1077,
    Brand: "Ariel",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1214198_1-ariel-detergent-washing-powder-matic-front-load.jpg",
  },
  {
    id: 622,
    quantity:0,
    Date: "Standard Delivery : 23 Jan",
    OFF: 22,
    QtyPiece: "Price of 1 Kg",
    QtyPieceForOneElement: "1 Kg",
    productName:
      "Garbage Bags - Oxo Biodegradable Medium, Green, (19x21 Inches)",
    productprice: 185.25,
    StrikePrice: 195,
    Brand: "BB Home",
    image:
      "https://www.bigbasket.com/media/uploads/p/s/1212117_3-bb-home-garbage-bags-oxo-biodegradable-medium-green-19x21-inches.jpg",
  },
];
